import { beforeEach, describe, expect, it, vi } from "vitest";
import { MemoristImportWorkflow, isSupportedImportFile } from "../../open-webui-integration/memorist/ui/importWorkflow";
import { renderMemoristSettingsPanel } from "../../open-webui-integration/memorist/ui/surfaces";

const dryReport = { import_run_uuid: "run-1", plan_fingerprint: "hash", created_at: "now", source_platform: "chatgpt", source_platform_display: "ChatGPT/OpenAI", detected_format: "chatgpt_conversation_mapping", conversation_count: 12, message_count: 340, eligible_processing_message_count: 280, ineligible_processing_message_count: 60, skip_reasons: { empty: 2 }, duplicate_conversation_count: 0, duplicate_message_count: 0, expected_new_database_rows: { sessions: 12, messages: 340, import_mappings: 352 }, expected_text_unitization_jobs: 0, expected_memory_processing_jobs: 280, processing_mode: "full_memory_reconstruction", processing_model: { role: "import_reconstruction", model_profile_uuid: null, provider_type: "openai_compatible_llm", model_name: "gpt-test", deterministic_fallback: false }, deterministic_fallback: false, graph_projection_enabled: true, large_reconstruction_warning: "May cost tokens" };
const finalReport = { import_run_uuid: "run-1", final_status: "completed_with_failures", terminal: true, last_error_sanitized: "Bearer sk-secret api_key=abc", imported_conversations: 12, imported_messages: 340, processing_jobs_total: 280, processing_jobs_pending: 0, processing_jobs_queued: 1, processing_jobs_running: 2, processing_jobs_retry_scheduled: 1, processing_jobs_succeeded: 270, processing_jobs_failed: 3, processing_jobs_skipped: 4, processing_jobs_already_processed: 5, memory_candidates_created: 6, memory_versions_created: 7, prompt_execution_runs: 8, model_usage_events: 9, input_tokens: 10, output_tokens: 11, graph_projection_outbox_events: 12, skip_reasons: { empty: 4 }, provider_breakdown: [{ operational_role: "import_reconstruction", model_profile_uuid: "profile-1", provider_type: "openai_compatible_llm", model_name: "gpt-test", processing_jobs: 280, input_tokens: 10, output_tokens: 11, succeeded: 270, failed: 3 }] };
let calls: Array<{ url: string; init?: RequestInit }> = [];

function json(body: unknown) { return Promise.resolve(new Response(JSON.stringify(body), { status: 200, headers: { "content-type": "application/json" } })); }
function setupFetch(status = "uploaded") { calls = []; vi.stubGlobal("fetch", vi.fn((url: string, init?: RequestInit) => { calls.push({ url, init }); if (url.includes("/imports?")) return json({ items: [] }); if (url.endsWith("/run-1")) return json({ import_run_uuid: "run-1", status }); if (url.endsWith("/dry-run-report")) return json(dryReport); if (url.endsWith("/processing-report")) return json(finalReport); if (url.endsWith("/progress")) return json({ import_run_uuid: "run-1", status, records_total: 1, records_done: 1 }); if (url.endsWith("/upload-file")) return json({ import_run_uuid: "run-1", status: "uploaded" }); if (url.endsWith("/inspect")) return json({ import_run_uuid: "run-1", status: "inspected" }); if (url.endsWith("/reconstruct")) return json({ import_run_uuid: "run-1", status: "reconstructed" }); if (url.endsWith("/dry-run")) return json({ import_run_uuid: "run-1", status: "dry_run" }); if (url.endsWith("/commit")) return json({ import_run_uuid: "run-1", status: "processing" }); if (url.endsWith("/process")) return json({ ok: true }); return json({ import_run_uuid: "run-1", status }); })); }
function mount(path = "/settings/memorist/import") { history.replaceState({}, "", path); const root = document.createElement("div"); document.body.append(root); const wf = new MemoristImportWorkflow(root); const match = path.match(/\/import\/([^/]+)/); wf.mount(match ? decodeURIComponent(match[1]) : undefined); return { root, wf }; }
async function tick() { await vi.waitFor(() => expect(calls.length).toBeGreaterThan(0)); await Promise.resolve(); await Promise.resolve(); }

beforeEach(() => { vi.useFakeTimers(); document.body.innerHTML = ""; vi.stubGlobal("XMLHttpRequest", undefined); setupFetch(); });

describe("import workflow", () => {
  it("mounts the custom element from settings route", () => { expect(renderMemoristSettingsPanel("/settings/memorist/import/run-1")?.tagName.toLowerCase()).toBe("memorist-import-workflow"); });
  it("accepts ZIP and rejects unsupported files", () => { expect(isSupportedImportFile(new File(["x"], "export.zip"))).toBe(true); expect(isSupportedImportFile(new File(["x"], "notes.txt"))).toBe(false); });
  it("selects ZIP and rejects unsupported in the DOM", () => { const { root } = mount(); const input = root.querySelector<HTMLInputElement>("input[type=file]")!; Object.defineProperty(input, "files", { value: [new File(["x"], "export.zip")], configurable: true }); input.dispatchEvent(new Event("change")); expect(root.textContent).toContain("export.zip"); Object.defineProperty(input, "files", { value: [new File(["x"], "bad.txt")], configurable: true }); input.dispatchEvent(new Event("change")); expect(root.textContent).toContain("Unsupported file type"); });
  it("multipart upload, inspect, reconstruct, and dry-run run in order", async () => { const { root } = mount(); const input = root.querySelector<HTMLInputElement>("input[type=file]")!; Object.defineProperty(input, "files", { value: [new File(["x"], "export.json")], configurable: true }); input.dispatchEvent(new Event("change")); root.querySelector<HTMLButtonElement>("[data-upload]")!.click(); await vi.waitFor(() => expect(calls.some(c => c.url.endsWith("/dry-run-report"))).toBe(true)); expect(calls.map(c => c.url)).toEqual(expect.arrayContaining(["/memcore/imports/upload-file", "/memcore/imports/run-1/inspect", "/memcore/imports/run-1/reconstruct", "/memcore/imports/run-1/dry-run", "/memcore/imports/run-1/dry-run-report"])); });
  it("renders dry-run report using backend field names", async () => { setupFetch("dry_run"); const { root } = mount("/settings/memorist/import/run-1"); await vi.waitFor(() => expect(root.textContent).toContain("Conversation count12")); expect(root.textContent).toContain("Conversation count12"); expect(root.textContent).toContain("Eligible processing messages280"); expect(root.textContent).toContain("Expected memory processing jobs280"); expect(root.textContent).toContain("gpt-test"); });
  it("keeps confirmation disabled before dry-run", () => { const { root } = mount(); expect(root.querySelector<HTMLInputElement>("[data-confirm]")!.disabled).toBe(true); });
  it("sends full reconstruction to dry-run and commit", async () => { setupFetch("dry_run"); const { root } = mount("/settings/memorist/import/run-1"); await vi.waitFor(() => expect(root.querySelector<HTMLInputElement>("[data-confirm]")!.disabled).toBe(false)); root.querySelector<HTMLInputElement>("[data-confirm]")!.click(); root.querySelector<HTMLButtonElement>("[data-commit]")!.click(); await tick(); const bodies = calls.filter(c => c.init?.method === "POST").map(c => String(c.init?.body)); expect(bodies.join("\n")).toContain("full_memory_reconstruction"); });
  it("changing mode invalidates approval", async () => { setupFetch("dry_run"); const { root } = mount("/settings/memorist/import/run-1"); await vi.waitFor(() => expect(root.textContent).toContain("Dry-run report")); const select = root.querySelector<HTMLSelectElement>("[data-processing-mode]")!; select.value = "none"; select.dispatchEvent(new Event("change")); expect(root.textContent).toContain("invalidated"); expect(root.querySelector<HTMLButtonElement>("[data-commit]")!.disabled).toBe(true); });
  it("refresh at dry-run restores report and confirmation", async () => { setupFetch("dry_run"); const { root } = mount("/settings/memorist/import/run-1"); await vi.waitFor(() => expect(root.textContent).toContain("Dry-run report")); expect(root.textContent).toContain("Dry-run report"); expect(root.querySelector<HTMLInputElement>("[data-confirm]")!.disabled).toBe(false); });
  it("refresh at uploaded and reconstructed do not call process", async () => { setupFetch("uploaded"); mount("/settings/memorist/import/run-1"); await tick(); setupFetch("reconstructed"); mount("/settings/memorist/import/run-1"); await tick(); expect(calls.some(c => c.url.endsWith("/process"))).toBe(false); });
  it("processing starts progress polling and committed stops polling", async () => { setupFetch("processing"); mount("/settings/memorist/import/run-1"); await vi.runOnlyPendingTimersAsync(); expect(calls.some(c => c.url.endsWith("/progress"))).toBe(true); setupFetch("committed"); mount("/settings/memorist/import/run-1"); await tick(); expect(calls.some(c => c.url.endsWith("/progress"))).toBe(false); });
  it("fully reconstructed loads and renders final report", async () => { setupFetch("fully_reconstructed"); const { root } = mount("/settings/memorist/import/run-1"); await vi.waitFor(() => expect(root.textContent).toContain("Processing report")); expect(root.textContent).toContain("Processing report"); expect(root.textContent).toContain("Imported conversations12"); });
  it("completed with failures enables retry", async () => { setupFetch("completed_with_failures"); const { root } = mount("/settings/memorist/import/run-1"); await vi.waitFor(() => expect(root.querySelector<HTMLButtonElement>("[data-retry]")!.disabled).toBe(false)); expect(root.querySelector<HTMLButtonElement>("[data-retry]")!.disabled).toBe(false); });
  it("polling calls do not overlap", async () => { let resolvers: Array<(r: Response) => void> = []; calls = []; vi.stubGlobal("fetch", vi.fn((url: string, init?: RequestInit) => { calls.push({ url, init }); if (url.includes("/imports?")) return json({items:[]}); if (url.endsWith("/run-1")) return json({import_run_uuid:"run-1",status:"processing"}); if (url.endsWith("/progress")) return new Promise<Response>(resolve => resolvers.push(resolve)); return json({}); })); mount("/settings/memorist/import/run-1"); await vi.runOnlyPendingTimersAsync(); await vi.advanceTimersByTimeAsync(5000); expect(calls.filter(c => c.url.endsWith("/progress")).length).toBe(1); resolvers[0](new Response(JSON.stringify({ import_run_uuid: "run-1", status: "processing" }))); });
  it("component disconnect stops timers", async () => { setupFetch("processing"); const { root, wf } = mount("/settings/memorist/import/run-1"); wf.disconnectedCallback(); await vi.runOnlyPendingTimersAsync(); expect(calls.filter(c => c.url.endsWith("/progress")).length).toBe(0); root.remove(); });
  it("sanitized errors are rendered without credentials", async () => { setupFetch("fully_reconstructed"); const { root } = mount("/settings/memorist/import/run-1"); await tick(); expect(root.textContent).not.toContain("sk-secret"); expect(root.textContent).not.toContain("api_key=abc"); });
});
