from __future__ import annotations

from typing import Any, Protocol


class ImportStore(Protocol):
    def create_run(self, archive_sha256: str, mode: str, options: dict[str, Any], target_workspace_uuid: str | None = None, target_project_uuid: str | None = None) -> dict[str, Any]: ...
    def get_run(self, import_run_uuid: str) -> dict[str, Any]: ...
    def update_run(self, import_run_uuid: str, values: dict[str, Any]) -> dict[str, Any]: ...
    def list_artifacts(self, import_run_uuid: str) -> list[dict[str, Any]]: ...
    def list_issues(self, import_run_uuid: str) -> list[dict[str, Any]]: ...
