import argparse
import hashlib
import json
import sqlite3
import tempfile
import zipfile
from pathlib import Path
from typing import Any

from memcore.imports.repositories import strip_none
from memcore.models import new_uuid, utc_now
from memcore.storage.migrations import apply_migrations
from memcore.storage.sqlite import connect
from memcore.validators.ijson import dump_ijson, load_ijson, validate_ijson_text
from memcore.version import __version__

DATA_TABLES = {
    "workspaces.ijsonl": "workspaces",
    "projects.ijsonl": "projects",
    "sessions.ijsonl": "sessions",
    "events.ijsonl": "session_events",
    "messages.ijsonl": "messages",
    "message_versions.ijsonl": "message_versions",
    "memory_processing_runs.ijsonl": "memory_processing_runs",
    "text_units.ijsonl": "text_units",
    "memory_candidates.ijsonl": "memory_candidates",
    "evidence.ijsonl": "candidate_evidence",
    "memories.ijsonl": "memories",
    "memory_versions.ijsonl": "memory_versions",
    "lineage.ijsonl": "memory_evidence_links",
    "blocks.ijsonl": "memory_blocks",
    "block_build_runs.ijsonl": "memory_block_build_runs",
    "block_versions.ijsonl": "memory_block_versions",
    "block_sources.ijsonl": "memory_block_sources",
    "attachments.ijsonl": "memory_context_attachments",
    "hot_cache.ijsonl": "session_hot_cache",
    "imports.ijsonl": "import_runs",
    "import_artifacts.ijsonl": "import_artifacts",
    "import_records.ijsonl": "import_records",
    "source_mappings.ijsonl": "import_mappings",
    "import_issues.ijsonl": "import_issues",
    "privacy_requests.ijsonl": "privacy_requests",
    "privacy_request_items.ijsonl": "privacy_request_items",
    "privacy_receipts.ijsonl": "erasure_receipts",
}


def export_heritage(
    connection: sqlite3.Connection,
    output_zip: str | Path,
    export_mode: str = "full",
    privacy_profile: str = "private-full",
) -> dict[str, Any]:
    with tempfile.TemporaryDirectory() as temp_dir:
        root = Path(temp_dir) / "memorist-heritage"
        (root / "data").mkdir(parents=True)
        (root / "schemas").mkdir()
        (root / "objects").mkdir()
        (root / "reports").mkdir()
        record_counts: dict[str, int] = {}
        for filename, table in DATA_TABLES.items():
            rows = [dict(row) for row in connection.execute(f"SELECT * FROM {table}")]
            record_counts[table] = len(rows)
            _write_ijsonl(root / "data" / filename, rows)
        manifest = {
            "format": "memorist-heritage",
            "format_version": "1.0",
            "package_uuid": new_uuid(),
            "created_at": utc_now(),
            "created_by": "memorist-core",
            "application_version": __version__,
            "schema_versions": _schema_versions(connection),
            "export_mode": export_mode,
            "base_package_uuid": None,
            "included_scopes": [],
            "record_counts": record_counts,
            "object_counts": {},
            "hash_algorithm": "sha256",
            "canonicalization": "RFC8785-compatible",
            "privacy_profile": privacy_profile,
            "encryption": None,
            "omissions": _privacy_omissions(privacy_profile),
        }
        (root / "manifest.ijson").write_text(dump_ijson(manifest), encoding="utf-8")
        (root / "schemas" / "heritage-manifest.schema.json").write_text("{}", encoding="utf-8")
        (root / "schemas" / "conversations.schema.json").write_text("{}", encoding="utf-8")
        (root / "schemas" / "memories.schema.json").write_text("{}", encoding="utf-8")
        (root / "reports" / "export-report.ijson").write_text(
            dump_ijson({"record_counts": record_counts, "privacy_profile": privacy_profile}),
            encoding="utf-8",
        )
        (root / "reports" / "human-readable-index.md").write_text(
            "# Memorist Heritage\n\nGenerated by memorist-core.\n",
            encoding="utf-8",
        )
        checksums = _checksums(root)
        (root / "checksums.sha256").write_text(
            "\n".join(f"{digest}  {path}" for path, digest in checksums.items()) + "\n",
            encoding="utf-8",
        )
        with zipfile.ZipFile(output_zip, "w", compression=zipfile.ZIP_DEFLATED) as package:
            for path in sorted(root.rglob("*")):
                if path.is_file():
                    package.write(path, path.relative_to(root.parent).as_posix())
    return inspect_heritage(output_zip)


def verify_heritage(package_path: str | Path) -> dict[str, Any]:
    issues: list[dict[str, object]] = []
    with zipfile.ZipFile(package_path) as archive:
        names = archive.namelist()
        _validate_package_paths(names)
        if "memorist-heritage/manifest.ijson" not in names:
            issues.append({"severity": "error", "issue_code": "missing_manifest"})
            return {"valid": False, "issues": issues}
        manifest_text = archive.read("memorist-heritage/manifest.ijson").decode("utf-8")
        validate_ijson_text(manifest_text)
        manifest = load_ijson(manifest_text)
        if manifest.get("format") != "memorist-heritage":
            issues.append({"severity": "error", "issue_code": "unsupported_format"})
        checksums_text = archive.read("memorist-heritage/checksums.sha256").decode("utf-8")
        expected = _parse_checksums(checksums_text)
        for relative_path, digest in expected.items():
            full_path = f"memorist-heritage/{relative_path}"
            if full_path not in names:
                issues.append(
                    {"severity": "error", "issue_code": "missing_payload", "path": relative_path}
                )
                continue
            actual = hashlib.sha256(archive.read(full_path)).hexdigest()
            if actual != digest:
                issues.append(
                    {"severity": "error", "issue_code": "checksum_mismatch", "path": relative_path}
                )
        for name in names:
            if name.endswith(".ijsonl"):
                for line in archive.read(name).decode("utf-8").splitlines():
                    if line.strip():
                        validate_ijson_text(line)
    return {"valid": not any(issue["severity"] == "error" for issue in issues), "issues": issues}


def inspect_heritage(package_path: str | Path) -> dict[str, Any]:
    verification = verify_heritage(package_path)
    with zipfile.ZipFile(package_path) as archive:
        manifest = load_ijson(archive.read("memorist-heritage/manifest.ijson").decode("utf-8"))
    return {"package_path": str(package_path), "manifest": manifest, "verification": verification}


def restore_heritage(
    package_path: str | Path,
    db_path: str | Path,
    dry_run: bool = True,
) -> dict[str, Any]:
    verification, counts, rows_by_table = _load_heritage_rows(package_path)
    if not verification["valid"]:
        return {"status": "invalid", "verification": verification}
    if dry_run:
        return {"status": "dry_run", "record_counts": counts, "verification": verification}
    connection = connect(db_path)
    try:
        apply_migrations(connection)
        return restore_heritage_into_connection(
            package_path,
            connection,
            dry_run=False,
            preloaded=(verification, counts, rows_by_table),
        )
    finally:
        connection.close()


def restore_heritage_into_connection(
    package_path: str | Path,
    connection: sqlite3.Connection,
    dry_run: bool = True,
    preloaded: tuple[dict[str, Any], dict[str, int], dict[str, list[dict[str, Any]]]] | None = None,
) -> dict[str, Any]:
    if preloaded is None:
        verification, counts, rows_by_table = _load_heritage_rows(package_path)
    else:
        verification, counts, rows_by_table = preloaded
    if not verification["valid"]:
        return {"status": "invalid", "verification": verification}
    if dry_run:
        return {"status": "dry_run", "record_counts": counts, "verification": verification}
    for table, rows in rows_by_table.items():
        columns = _table_columns(connection, table)
        for row in rows:
            filtered = {key: value for key, value in row.items() if key in columns}
            if not filtered:
                continue
            placeholders = ", ".join("?" for _ in filtered)
            quoted_columns = ", ".join(filtered)
            connection.execute(
                f"INSERT OR IGNORE INTO {table} ({quoted_columns}) VALUES ({placeholders})",
                tuple(filtered.values()),
            )
    connection.commit()
    return {"status": "restored", "record_counts": counts, "verification": verification}


def _load_heritage_rows(
    package_path: str | Path,
) -> tuple[dict[str, Any], dict[str, int], dict[str, list[dict[str, Any]]]]:
    verification = verify_heritage(package_path)
    if not verification["valid"]:
        return verification, {}, {}
    with zipfile.ZipFile(package_path) as archive:
        counts: dict[str, int] = {}
        rows_by_table: dict[str, list[dict[str, Any]]] = {}
        for filename, table in DATA_TABLES.items():
            name = f"memorist-heritage/data/{filename}"
            rows = [
                load_ijson(line)
                for line in archive.read(name).decode("utf-8").splitlines()
                if line.strip()
            ]
            counts[table] = len(rows)
            rows_by_table[table] = rows
    return verification, counts, rows_by_table


def _write_ijsonl(path: Path, rows: list[dict[str, Any]]) -> None:
    path.write_text(
        "\n".join(dump_ijson(strip_none(row)) for row in rows) + ("\n" if rows else ""),
        encoding="utf-8",
    )


def _schema_versions(connection: sqlite3.Connection) -> dict[str, str]:
    return {
        row["migration_id"]: row["checksum"]
        for row in connection.execute("SELECT migration_id, checksum FROM schema_migrations")
    }


def _privacy_omissions(profile: str) -> list[str]:
    if profile == "portable_redacted":
        return ["sensitive_memories", "raw_messages", "attachments", "usage_telemetry"]
    return []


def _checksums(root: Path) -> dict[str, str]:
    checksums: dict[str, str] = {}
    for path in sorted(root.rglob("*")):
        if path.is_file() and path.name != "checksums.sha256":
            relative = path.relative_to(root).as_posix()
            checksums[relative] = hashlib.sha256(path.read_bytes()).hexdigest()
    return checksums


def _parse_checksums(text: str) -> dict[str, str]:
    parsed: dict[str, str] = {}
    for line in text.splitlines():
        digest, relative_path = line.split("  ", 1)
        parsed[relative_path] = digest
    return parsed


def _validate_package_paths(names: list[str]) -> None:
    for name in names:
        path = Path(name)
        if path.is_absolute() or ".." in path.parts:
            raise ValueError("unsafe heritage package path")


def _table_columns(connection: sqlite3.Connection, table: str) -> set[str]:
    return {row["name"] for row in connection.execute(f"PRAGMA table_info({table})")}


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("command", choices=["verify", "inspect", "restore", "compare"])
    parser.add_argument("package")
    parser.add_argument("--db-path")
    parser.add_argument("--other-db-path")
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()
    if args.command == "verify":
        print(json.dumps(verify_heritage(args.package), indent=2))
    elif args.command == "inspect":
        print(json.dumps(inspect_heritage(args.package), indent=2))
    elif args.command == "compare":
        if not args.db_path or not args.other_db_path:
            raise SystemExit("--db-path and --other-db-path are required for compare")
        from memcore.heritage.comparator import compare_databases

        print(json.dumps(compare_databases(args.db_path, args.other_db_path), indent=2))
    else:
        if not args.db_path:
            raise SystemExit("--db-path is required for restore")
        print(json.dumps(restore_heritage(args.package, args.db_path, args.dry_run), indent=2))


if __name__ == "__main__":
    main()
